name: Package Source Code As package.zip on Release

on:
  release:
    types: [created]

jobs:
  package-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Package source code as zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'package.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload package.zip
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "package.zip"
          path: package.zip
          token: ${{ secrets.GITHUB_TOKEN }}
